logging.level.web: INFO

spring:
  datasource:
    url: jdbc:h2:memory:test_db;INIT=create schema if not exists test_db
    driver-class-name: org.h2.Driver
    username: sa
    password: root@2020!!!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console