logging.level.web: INFO

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    driver-class-name: com.mysql.cj.jdbc.driver
    username: sa111
    password: "{cipher}c0aae89b7b8ef3ce2afa291da12ff4cd38bbad58511ef7215dd6438ca058acb0"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
