logging.level.web: INFO

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    driver-class-name: com.mysql.cj.jdbc.driver
    username: sa
    password: root@2020!!!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
