server:
  port: 8888

# git backend
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:nkcoder/springcloud-samples.git
          search-paths: config-repo/orderservice, config-repo/stockservice
#          uri: https://github.com/nkcoder/springcloud-samples
#          username: daniel5hbs@gmail.com
#          password: your-password-for-github
