server:
  port: 8888

# git backend
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nkcoder/springcloud-samples
          search-paths: config-repo/orderservice, config-repo/stockservice
          username: daniel5hbs@gmail.com
          password: rR_MzHLwX2nUursPZ.K_
